[theme]
base = "light"
primaryColor = "#0C1BA8"
backgroundColor = "#F6F5F2"
secondaryBackgroundColor = "#ffffff"
textColor = "#1A1A1A"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
